CREATE DATABASE open_finance;
USE open_finance;

CREATE TABLE `open_finance`.`tb_registros` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NOT NULL,
  `VALOR` DECIMAL(10,2) NOT NULL,
  `DAT` DATE NOT NULL,
  `TIPO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));